### ISSUE TITLE
HTML proofer not ignoring directories

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/governance#28]
HTML proofer is not ignoring directories that it should be. I've played with the ruby regex using Rubular and it should be correct. but it's obviously not working. it works on the first URL but not the second. 

[opened an issue about this HERE](https://github.com/gjtorikian/html-proofer/issues/775) in hopes someone can point me to what i'm doing incorrectly in the ruby regex syntax. 

```
uses: chabad360/htmlproofer@master
        with:
          directory: '_build/html'
          arguments: |
           --ignore-files "/.+\/_static/, /.+\/reference\/meeting-notes.+/"
       
      - name: Push to gh-pages branch for publication from main
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_build/html
```

THIS so post was also helpful - https://stackoverflow.com/questions/29678646/can%C2%B4t-get-htmlproof-to-accept-an-ignore-pattern 

i'm struggling to install it locally because it wants ruby 3.x and i have 2.x running. worried it will break my website build to install 3.x - don't have the energy to fix the website right now. min mistakes wants 2.x it seems.
